version: "3"
services:
  db:
    build: database/.
    restart: always
    ports:
      - "3306:3306"
  faice-api:
    build: faice-api/.
    restart: always
    depends_on: 
      - "db"
    ports:
      - "5000:5000"